// @id pIbJFVnCUMqyEl1n94ERNX
// @title Overview
getTransformOverview('QUERY')

// @id qp76cfguBXuJYWpg3zUFMn
// @title QUERY Class
__QUERY = class extends Transform {
  getParams() {
    return queryParams;
  }

  async getData() {
    return queryData(this.spec, this.meta);
  }

  async getMeta() {
    return queryMeta(this.spec, this.meta);
  }
}

// @id WbaWsdyIutOMhr5Oba8Qwj
// @title QUERY Params
queryParams = [
  {
    id: 'query',
    control: 'QueryEditor',
    required: true,
  },
  {
    id: 'schema',
    name: 'Schema',
    label: 'Output table schema',
    hint: 'Schema of the table generated by the SQL query',
    icon: 'mdi-graph-outline',
    control: 'SchemaEditor',
  },
];

// @id rpvsNtfx2UHS3GsXIkM4nD
// @title QUERY Data
queryData = function (spec, meta) {
  return [];
}

// @id pe9IrX7FXEFogfKrONRtLq
// @title QUERY Meta
queryMeta = function (spec, meta) {
  return meta;
}